language: ruby
cache: bundler
rvm:
  - 2.3.0
before_script:
- bundle exec rails db:create --all
- bundle exec rails db:migrate
services:
- postgresql
deploy:
  provider: heroku
  app:
    develop: robot-man-api
  on:
    repo: kriizjones/robot_man_challenge
  run:
  - bundle exec rails db:migrate